export const url = {
  baseURL: 'https://dummyjson.com',
  accData: '/user/me',
  accAdd: '/users/add',
  accAction: '/users/',
  login: '/auth/login',
  refreshSession: '/auth/refresh',
  categories: '/products/category-list',
  product: '/products/',
  categoryProducts: '/products/category/',
  brands: '/products',
  search: '/products/search',
  sendOrder: '/carts/add',
  getOrders: '/carts/user/',
}
